### ISSUE TITLE
Slideshow of quotes

### ISSUE THREAD

**Issue by carmonamateo** [agrothendieck/agrothendieck.github.io#4]
Dear @nojb,

Can you help me creating a slideshow for quotes, I have tried but it is still not working. It is on the "index" file, at the end.

- The Next & previous buttons are not in the right place
- There is a gray around the buttons, and it is better the color of the page, as in the images of the top.
- The slides seems to continue forever and we have online three quotes.

Many thanks if you can help

**Comment by nojb** [comment]
Hello,
I took a quick look. The main problem is, I think, that the JavaScript code that implements the slide show assumes that there is only one slide show in the page. By defining a second slide show in the page, the code gets confused which is why the result does not make sense. There is also something wrong with the placement of the Next & Prev buttons, but this is secondary.

I see two alternatives:
1) rework the JavaScript code to allow more than one slide show per page. This will take some work.
2) switch to a different slide show implementation that already supports more than one slide show per page. I am not very familiar with these things personally.

**Comment by carmonamateo** [comment]
Many thanks,

The problems seems to be solved [here](https://stackoverflow.com/questions/43299759/how-do-i-make-multiple-slideshows-in-the-same-html-document/43300869), I tried it without success...
